  
name: publish-on-tag

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: | 
          yarn compile && yarn publish